-- MySQL Script generated by MySQL Workbench
-- Fri Apr 28 01:58:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`uloga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`uloga` ;

CREATE TABLE IF NOT EXISTS `project`.`uloga` (
  `idUloga` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUloga`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`korisnik` ;

CREATE TABLE IF NOT EXISTS `project`.`korisnik` (
  `idKorisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Uloga_idUloga` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`),
  INDEX `fk_Korisnik_Uloga_idx` (`Uloga_idUloga` ASC) VISIBLE,
  CONSTRAINT `fk_Korisnik_Uloga`
    FOREIGN KEY (`Uloga_idUloga`)
    REFERENCES `project`.`uloga` (`idUloga`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`zgrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`zgrada` ;

CREATE TABLE IF NOT EXISTS `project`.`zgrada` (
  `idZgrada` INT NOT NULL AUTO_INCREMENT,
  `godinaIzgradnje` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `grad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZgrada`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`stan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`stan` ;

CREATE TABLE IF NOT EXISTS `project`.`stan` (
  `idStan` INT NOT NULL AUTO_INCREMENT,
  `cena` DOUBLE NOT NULL,
  `kvadratura` DOUBLE NOT NULL,
  `sprat` INT NOT NULL,
  `opis` VARCHAR(300) NOT NULL,
  `Zgrada_idZgrada` INT NOT NULL,
  `Korisnik_idKorisnik` INT NOT NULL,
  `broj` INT NOT NULL,
  PRIMARY KEY (`idStan`),
  INDEX `fk_Stan_Zgrada1_idx` (`Zgrada_idZgrada` ASC) VISIBLE,
  INDEX `fk_Stan_Korisnik1_idx` (`Korisnik_idKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_Stan_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnik`)
    REFERENCES `project`.`korisnik` (`idKorisnik`),
  CONSTRAINT `fk_Stan_Zgrada1`
    FOREIGN KEY (`Zgrada_idZgrada`)
    REFERENCES `project`.`zgrada` (`idZgrada`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`komentar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`komentar` ;

CREATE TABLE IF NOT EXISTS `project`.`komentar` (
  `idKomentar` INT NOT NULL AUTO_INCREMENT,
  `komentar` VARCHAR(300) NOT NULL,
  `Stan_idStan` INT NOT NULL,
  `Korisnik_idKorisnik` INT NOT NULL,
  PRIMARY KEY (`idKomentar`),
  INDEX `fk_Komentar_Stan1_idx` (`Stan_idStan` ASC) VISIBLE,
  INDEX `fk_Komentar_Korisnik1_idx` (`Korisnik_idKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_Komentar_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnik`)
    REFERENCES `project`.`korisnik` (`idKorisnik`),
  CONSTRAINT `fk_Komentar_Stan1`
    FOREIGN KEY (`Stan_idStan`)
    REFERENCES `project`.`stan` (`idStan`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`obilazak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`obilazak` ;

CREATE TABLE IF NOT EXISTS `project`.`obilazak` (
  `idObilazak` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NOT NULL,
  `vreme` VARCHAR(45) NOT NULL,
  `potvrdaObilaska` INT NOT NULL,
  `Korisnik_idKorisnik` INT NOT NULL,
  `Stan_idStan` INT NOT NULL,
  `napomena` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idObilazak`),
  INDEX `fk_Obilazak_Korisnik1_idx` (`Korisnik_idKorisnik` ASC) VISIBLE,
  INDEX `fk_Obilazak_Stan1_idx` (`Stan_idStan` ASC) VISIBLE,
  CONSTRAINT `fk_Obilazak_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnik`)
    REFERENCES `project`.`korisnik` (`idKorisnik`),
  CONSTRAINT `fk_Obilazak_Stan1`
    FOREIGN KEY (`Stan_idStan`)
    REFERENCES `project`.`stan` (`idStan`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`omiljenistanovi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`omiljenistanovi` ;

CREATE TABLE IF NOT EXISTS `project`.`omiljenistanovi` (
  `idOmiljeniStanovi` INT NOT NULL AUTO_INCREMENT,
  `Korisnik_idKorisnik` INT NOT NULL,
  `Stan_idStan` INT NOT NULL,
  PRIMARY KEY (`idOmiljeniStanovi`),
  INDEX `fk_OmiljeniStanovi_Korisnik1_idx` (`Korisnik_idKorisnik` ASC) VISIBLE,
  INDEX `fk_OmiljeniStanovi_Stan1_idx` (`Stan_idStan` ASC) VISIBLE,
  CONSTRAINT `fk_OmiljeniStanovi_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnik`)
    REFERENCES `project`.`korisnik` (`idKorisnik`),
  CONSTRAINT `fk_OmiljeniStanovi_Stan1`
    FOREIGN KEY (`Stan_idStan`)
    REFERENCES `project`.`stan` (`idStan`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`prodaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`prodaja` ;

CREATE TABLE IF NOT EXISTS `project`.`prodaja` (
  `idProdaja` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NOT NULL,
  `Stan_idStan` INT NOT NULL,
  `Korisnik_idKorisnik` INT NOT NULL,
  PRIMARY KEY (`idProdaja`),
  INDEX `fk_Prodaja_Stan1_idx` (`Stan_idStan` ASC) VISIBLE,
  INDEX `fk_Prodaja_Korisnik1_idx` (`Korisnik_idKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_Prodaja_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnik`)
    REFERENCES `project`.`korisnik` (`idKorisnik`),
  CONSTRAINT `fk_Prodaja_Stan1`
    FOREIGN KEY (`Stan_idStan`)
    REFERENCES `project`.`stan` (`idStan`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`slika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`slika` ;

CREATE TABLE IF NOT EXISTS `project`.`slika` (
  `idSlika` INT NOT NULL AUTO_INCREMENT,
  `root` LONGBLOB NULL DEFAULT NULL,
  `Stan_idStan` INT NOT NULL,
  PRIMARY KEY (`idSlika`),
  INDEX `fk_Slika_Stan1_idx` (`Stan_idStan` ASC) VISIBLE,
  CONSTRAINT `fk_Slika_Stan1`
    FOREIGN KEY (`Stan_idStan`)
    REFERENCES `project`.`stan` (`idStan`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
